import { describe,it,expect } from 'vitest';
import { BattleSim, DT } from '../../src/core/sim';
import { damageFormula } from '../../src/core/systems/combat';
import { getSkill, heroes, stages } from '../../src/core/data';
describe('combat contracts',()=>{
  it('uses squared attack and non-negative mitigation with a one-point floor',()=>{expect(damageFormula(100,100)).toBe(50);expect(damageFormula(200,0)).toBe(200);expect(damageFormula(1,1000)).toBe(1);});
  it('uses resistance for magic; healing ignores resistance',()=>{const s=new BattleSim();const u=s.allies[0],v=s.enemies[0];v.stats.def=0;v.stats.mres=100;const before=v.hp;s.damage(u,v,100,'magic');expect(before-v.hp).toBe(50);s.heal(u,v,40);expect(v.hp).toBe(before-10);});
  it('absorbs shield before HP and awards successful attack / hit energy',()=>{const s=new BattleSim();const u=s.allies[0],v=s.enemies[0];s.applyStatus(u,{kind:'shield',duration:6,magnitude:400},u.id);s.damage(v,u,300,'true',true);expect(u.hp).toBe(u.stats.hp);expect(u.energy).toBe(8);expect(u.statuses[0].magnitude).toBe(100);s.damage(u,v,20,'true',true);expect(u.energy).toBe(20);});
  it('caps energy and does not allow dead heroes to collect it',()=>{const s=new BattleSim();const u=s.allies[0];u.energy=99.999;s.step();expect(u.energy).toBe(100);s.damage(s.enemies[0],u,99999,'true');const old=u.energy;s.step();expect(u.energy).toBe(old);expect(s.allies[1].energy).toBeGreaterThanOrEqual(15);});
  it('regenerates two energy per second',()=>{const s=new BattleSim();for(let i=0;i<60;i++)s.step();expect(s.allies[0].energy).toBeCloseTo(2,8);});
  it('refreshes same-kind statuses without stacking and halves boss stun',()=>{const s=new BattleSim(5);const u=s.allies[0];s.applyStatus(u,{kind:'stun',duration:2,magnitude:0},u.id);s.applyStatus(u,{kind:'stun',duration:1,magnitude:0},u.id);expect(u.statuses).toHaveLength(1);expect(u.statuses[0].duration).toBe(2);u.boss=true;u.statuses=[];s.applyStatus(u,{kind:'stun',duration:2,magnitude:0},u.id);expect(u.statuses[0].duration).toBe(1);});
  it.each(['stun','silence','airborne','knockback'] as const)('%s interrupts a casting enemy without resolving its spell',kind=>{const s=new BattleSim(4);const v=s.enemies[0];v.casting={skillId:'swamp_hex',remaining:.01,total:2.5};s.applyStatus(v,{kind,duration:2,magnitude:200},s.allies[0].id);expect(v.casting).toBeUndefined();expect(s.events.at(-1)?.type).toBe('interrupt');const hp=s.allies.map(u=>u.hp);s.step();expect(s.allies.map(u=>u.hp)).toEqual(hp);});
  it('ticks all four seconds of a four-second DoT and expires safely on death',()=>{const s=new BattleSim();const v=s.enemies[0];v.stats.moveSpeed=0;v.x=5700;v.hp=v.stats.hp=5000;const before=v.hp;s.applyStatus(v,{kind:'dot',duration:4,magnitude:60},s.allies[0].id);for(let i=0;i<240;i++)s.step();expect(before-v.hp).toBeCloseTo(4*damageFormula(60,v.stats.mres),6);expect(v.statuses).toHaveLength(0);});
  it('requires exactly five unique, known heroes',()=>{expect(()=>new BattleSim(1,1,['ironwall'])).toThrow();expect(()=>new BattleSim(1,1,Array(5).fill('ironwall'))).toThrow();});
  it('contains the full six heroes and ten stages',()=>{expect(heroes).toHaveLength(6);expect(stages).toHaveLength(10);expect(heroes.map(h=>getSkill(h.skillId).aimType)).toContain('target_ally');});
});
describe('aiming and inputs',()=>{
  it('rejects out-of-range ground aiming without spending energy',()=>{const s=new BattleSim();const u=s.allies[0];u.energy=100;expect(s.cast(u.id,{x:5600,y:820})).toBe(false);expect(u.energy).toBe(100);});
  it('resolves ground AoE and consumes energy once',()=>{const s=new BattleSim();const u=s.allies[0];u.energy=100;for(const v of s.enemies)v.x=u.x+300;expect(s.cast(u.id,{x:u.x+300,y:820})).toBe(true);expect(u.energy).toBe(0);expect(s.enemies.every(v=>v.hp<v.stats.hp&&v.statuses.some(x=>x.kind==='stun'))).toBe(true);expect(s.cast(u.id,{x:u.x+300,y:820})).toBe(false);});
  it('heals only the selected living ally and creates a shield',()=>{const s=new BattleSim();const u=s.allies[4],v=s.allies[0];u.energy=100;v.hp-=900;expect(s.cast(u.id,{x:v.x,y:v.y,targetId:v.id})).toBe(true);expect(v.hp).toBe(v.stats.hp-200);expect(v.statuses.find(x=>x.kind==='shield')?.magnitude).toBe(400);});
  it('rejects wrong-team targets, dead targets, nonfinite and over-angle inputs',()=>{const s=new BattleSim();const u=s.allies[4];u.energy=100;const v=s.enemies[0];expect(s.cast(u.id,{x:u.x,y:u.y,targetId:v.id})).toBe(false);expect(s.enqueue({tick:1,type:'cast',unitId:u.id,aim:{x:NaN,y:800}})).toBe(false);const archer=s.allies[3];archer.energy=100;expect(s.cast(archer.id,{x:900,y:800,angle:Math.PI})).toBe(false);});
  it('direction hits units on the beam and misses units outside its width',()=>{const s=new BattleSim();const u=s.allies[3];u.energy=100;const [a,b,c]=s.enemies;a.x=u.x+400;a.y=u.y;b.x=u.x+600;b.y=u.y+300;c.x=u.x-100;c.y=u.y;s.cast(u.id,{x:u.x+1000,y:u.y,angle:0});expect(a.hp).toBeLessThan(a.stats.hp);expect(b.hp).toBe(b.stats.hp);expect(c.hp).toBe(c.stats.hp);});
  it('supports target_enemy and none aim without changing the roster',()=>{const s=new BattleSim();const u=s.allies[0],v=s.enemies[0];u.skillId='phantom_strike';u.energy=100;v.x=u.x+500;expect(s.cast(u.id,{x:v.x,y:v.y,targetId:v.id})).toBe(true);expect(v.statuses.some(x=>x.kind==='airborne')).toBe(true);u.skillId='rally';u.energy=100;expect(s.cast(u.id,{x:u.x,y:u.y})).toBe(true);expect(s.allies.every(v=>v.statuses.some(x=>x.kind==='atk_up'))).toBe(true);});
  it('silence and hard control prevent energy spending',()=>{const s=new BattleSim();const u=s.allies[0];u.energy=100;s.applyStatus(u,{kind:'silence',duration:2,magnitude:0},s.enemies[0].id);expect(s.cast(u.id,{x:u.x+100,y:820})).toBe(false);expect(u.energy).toBe(100);});
});
describe('campaign determinism',()=>{
  it('replays the same seed and input timeline with the same snapshot across render batch sizes',()=>{const a=new BattleSim(3,2222),b=new BattleSim(3,2222);for(const s of [a,b]){s.enqueue({tick:100,type:'auto',enabled:true});s.enqueue({tick:500,type:'auto',enabled:false});}for(let i=0;i<1200;i++)a.step();for(let frame=0;frame<300;frame++)for(let i=0;i<4;i++)b.step();expect(a.snapshot()).toBe(b.snapshot());expect(a.tick*DT).toBe(20);});
  it('clears a wave, marches three seconds, and carries health and energy',()=>{const s=new BattleSim();const u=s.allies[0];u.hp-=100;u.energy=40;for(const v of s.enemies)s.damage(u,v,99999,'true');s.step();expect(s.intermission).toBe(180);const x=u.x;for(let i=0;i<180;i++)s.step();expect(s.wave).toBe(1);expect(u.hp).toBe(u.stats.hp-100);expect(u.energy).toBeGreaterThan(40);expect(u.x).toBeGreaterThan(x);expect(s.enemies).toHaveLength(4);expect(u.casting).toBeUndefined();});
  it('rates surviving heroes and resolves a total defeat',()=>{const s=new BattleSim();for(const v of s.allies)s.damage(s.enemies[0],v,99999,'true');s.step();expect(s.result).toMatchObject({victory:false,stars:0,reason:'defeat'});const win=BattleSim.runHeadless(1,1,'auto');expect(win).toMatchObject({victory:true,stars:3,wave:2});});
  it('matches repeated complete headless results',()=>{expect(BattleSim.runHeadless(3,90210,'auto')).toEqual(BattleSim.runHeadless(3,90210,'auto'));});
  it('keeps the second melee hero fighting after knockback rather than stranding them behind the tank',()=>{const r=BattleSim.runHeadless(3,1,'auto');expect(r.damage.lancer).toBeGreaterThan(1000);});
});
