import { writeFileSync } from 'node:fs';
import { BattleSim } from '../src/core/sim';
import { stages } from '../src/core/data';
import type { Policy } from '../src/core/types';
const rows:string[]=['# HERO RUSH balance report','', '20 seeds (1–20), default five heroes, 60 Hz. Generated by `npm run balance`.','', '| Stage | Auto wins | No ultimate wins | Tactical wins | Auto time |','|---|---:|---:|---:|---:|'];
let pass=true;
for(const stage of stages) {
  const runs=(['auto','noUlt','tactical'] as Policy[]).map(policy=>Array.from({length:20},(_,i)=>BattleSim.runHeadless(stage.id,i+1,policy)));
  const rates=runs.map(list=>list.filter(r=>r.victory).length*5);
  if((stage.id<=3&&rates[0]!==100)||(stage.id>=8&&rates[0]>50)) pass=false;
  const row=`| 1-${stage.id} | ${rates[0]}% | ${rates[1]}% | ${rates[2]}% | ${(runs[0].reduce((s,r)=>s+r.seconds,0)/20).toFixed(1)} s |`;
  rows.push(row);console.log(row);
}
rows.push('',`Required gates: ${pass?'PASS':'FAIL'}. Stages 1–3 auto 100%; stages 8–10 auto ≤50%.`,'','Tactical is a deterministic comparison policy: reserve control for enemy casts, heal below 65%, aim AoE at clusters. It is not a claim of human play-test success.','Level scaling applies to HP, attack, defense and resistance; hero base stats and the damage formula match the brief. No criticals or hidden random damage.');
writeFileSync('tests/balance-report.md',rows.join('\n')+'\n');
if(!pass)process.exitCode=1;
